SELECT 1 FROM dbc.tablesv
WHERE databasename = '${DW_AMBIENTE}_STAGING' AND TRIM(TABLENAME) = 'DATOS_PERSONALES';

.IF ACTIVITYCOUNT = 0 THEN .GOTO NEXT

DROP TABLE ${DW_AMBIENTE}_STAGING.DATOS_PERSONALES;

.LABEL NEXT

CREATE SET TABLE ${DW_AMBIENTE}_STAGING.DATOS_PERSONALES ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     
     (
      nombre VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      apellido VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      dni INTEGER,
      nacimiento_fc DATE FORMAT 'YY/MM/DD')
PRIMARY INDEX ( dni );
